version: '3.4'

volumes:
  djangoauth-image-data:

services:
  djangoauth-image:
    image: maxmello/activeannoauth:0.1
    command: bash -c "python manage.py migrate && python manage.py createsu && python manage.py runserver 0.0.0.0:8051"
    volumes:
      - djangoauth-image-data:/data
    environment:
      ADMIN_PASSWORD: mysecretpassword
      DATA_PATH: /data
    ports:
      - 8051:8051