
export const FinalizeAnnotationPolicy = [
    'EXPORT_EVERY_ANNOTATION_SEPARATELY', 'MAJORITY_VOTE_PER_ANNOTATION_OR_CURATOR', 'MAJORITY_VOTE_WHOLE_DOCUMENT_OR_CURATOR', 'ALWAYS_REQUIRE_CURATION', 'MAJORITY_VOTE_PER_ANNOTATION_OR_ADDITIONAL_ANNOTATOR', 'MAJORITY_VOTE_WHOLE_DOCUMENT_OR_ADDITIONAL_ANNOTATOR'
];