// @flow

import type {Dictionary} from "../types/Types";

export const FinalizeAnnotationPolicies: Dictionary<string, string> = {
    EXPORT_EVERY_ANNOTATION_SEPARATELY: 'EXPORT_EVERY_ANNOTATION_SEPARATELY',
    MAJORITY_VOTE_PER_ANNOTATION_OR_CURATOR: 'MAJORITY_VOTE_PER_ANNOTATION_OR_CURATOR',
    MAJORITY_VOTE_WHOLE_DOCUMENT_OR_CURATOR: 'MAJORITY_VOTE_WHOLE_DOCUMENT_OR_CURATOR',
    ALWAYS_REQUIRE_CURATION: 'ALWAYS_REQUIRE_CURATION',
    MAJORITY_VOTE_PER_ANNOTATION_OR_ADDITIONAL_ANNOTATOR: 'MAJORITY_VOTE_PER_ANNOTATION_OR_ADDITIONAL_ANNOTATOR',
    MAJORITY_VOTE_WHOLE_DOCUMENT_OR_ADDITIONAL_ANNOTATOR: 'MAJORITY_VOTE_WHOLE_DOCUMENT_OR_ADDITIONAL_ANNOTATOR'
};

export type FinalizeAnnotationPolicy = $Keys<typeof FinalizeAnnotationPolicies>;